language: node_js
node_js:
  - "11.6.0"
cache:
  yarn: true
script:
  - BENCHMARK_SAMPLES=100 yarn run build-website && cp dist/index.html dist/404.html && yarn start --count 0 --csv report.csv
deploy:
  - provider: pages
    local-dir: ./dist/
    fqdn: serialize-comparison.jaid.codes
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # https://github.com/settings/tokens
  - provider: releases
    file: report.csv
    skip-cleanup: true
    api-key: $GITHUB_TOKEN
    on:
      tags: true